nome=input("Digite seu nome: ")
endereco=input("Digite o seu endereço: ")
numero=int(input("Digite o numero: "))
telefone=input("Digite seu telefone: ")
print("Nome: ",nome)
print("Endereço: ",endereco)
print("Número: ",numero)
print("Telefone:", telefone)
