altura=int(input("Digite a altura do retângulo: "))
base=int(input("Digite a base do retângulo: "))
perimetro= 2*(altura+base)
area= (altura*base)
print("O perimetro do seu retângulo é ",perimetro,"cm²",', e a área é ',area,"cm².")